### ISSUE TITLE
Eu tenho um erro ao gerar a hash

### ISSUE THREAD

**Issue by thiagosmagalhaes** [kayque7k/Wirecard_gateway_for_flutter#2]
Erro é apresentado no console e o retorno de encryptCard é ""

> W/System.err(27604): java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
W/System.err(27604): 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:287)
W/System.err(27604): 	at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:55)
W/System.err(27604): 	at java.security.KeyFactory.generatePublic(KeyFactory.java:361)
W/System.err(27604): 	at com.example.wirecard.CreditCard.encrypt(CreditCard.java:131)
W/System.err(27604): 	at com.example.wirecard.WirecardPlugin.onMethodCall(WirecardPlugin.kt:51)
W/System.err(27604): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err(27604): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(27604): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err(27604): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(27604): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err(27604): 	at android.os.Looper.loop(Looper.java:183)
W/System.err(27604): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
W/System.err(27604): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27604): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
W/System.err(27604): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
W/System.err(27604): Caused by: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
W/System.err(27604): 	at com.android.org.conscrypt.NativeCrypto.EVP_parse_public_key(Native Method)
W/System.err(27604): 	at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:285)
W/System.err(27604): 	... 14 more
I/flutter (27604):

**Comment by thiagosmagalhaes** [comment]
Conseguir resolver, olhei a documentação oficial da wirecard para android, na minha string publickey eu devo colocar \n no final de cada linha, ficando assim:

> String publicKey = "-----BEGIN PUBLIC KEY-----\n"
              "MIIBIjANBgkqhkiG9w0BAQasdasdAAOCAQ8AMIIBCgKCAQEAmutpuVl98tmJ75vmozhj\n"
              "YrAVVb3dLptyyZglhPLTpasdasdqb6F7lU5wX8HF8p21fmcv1/dZkIjb49cafYv6+m6\n"
              "asdfssdfasdf79a8sdf9a7s9d8fdfsdf/ozsz8g9lZ2PALHINbblfTUa4zUqQPS7FrNt\n"
              "CB+D96sjCvr545fTg70cs4ITr9hBjFvS+Y0DBeldN2wBX3GtukaHds8VorBnLQuT\n"
              "RG4RCuiWOJsLw+dXObuUZ/IAAtS2T1AXp+cCSuBIXLGmO42MI3v9fqGftE1XL8gI\n"
              "uhLE6HXgFnza/w6mbuLYnDnMjmugzFZ6S2frDWH4MeiNdPxLJtP4XxIYLmQHX+Pz\n"
              "ZwIDAQAB\n"
              "-----END PUBLIC KEY-----";
